import type { FarmStoreState } from "@/store/farm";
import type { DemoField } from "./types";

export const demoFields: DemoField[] = [
  {
    id: "A-12",
    name: "A-12 地块",
    crop: "柑橘",
    variety: "晚熟脐橙",
    area: 2.4,
    growthStage: "果实膨大期",
    phenologyProgress: 68,
    health: 72,
    ndvi: 0.72,
    soilMoisture: 84,
    rainfall14d: 58,
    elevation: 320,
    slope: 5,
    soilType: "紫色土",
    status: "risk",
    statusLabel: "叶片异常",
    latitude: 30.952,
    longitude: 108.697,
  },
  {
    id: "B-03",
    name: "B-03 地块",
    crop: "柑橘",
    variety: "晚熟脐橙",
    area: 2.1,
    growthStage: "果实膨大期",
    phenologyProgress: 72,
    health: 76,
    ndvi: 0.76,
    soilMoisture: 78,
    rainfall14d: 58,
    elevation: 318,
    slope: 4,
    soilType: "紫色土",
    status: "attention",
    statusLabel: "注意关注",
    latitude: 30.958,
    longitude: 108.705,
  },
  {
    id: "B-04",
    name: "B-04 地块",
    crop: "柑橘",
    variety: "晚熟脐橙",
    area: 3.5,
    growthStage: "采收窗口",
    phenologyProgress: 88,
    health: 91,
    ndvi: 0.81,
    soilMoisture: 69,
    rainfall14d: 58,
    elevation: 324,
    slope: 6,
    soilType: "紫色土",
    status: "attention",
    statusLabel: "采收窗口",
    latitude: 30.959,
    longitude: 108.711,
  },
  {
    id: "C-02",
    name: "C-02 地块",
    crop: "柑橘",
    variety: "晚熟脐橙",
    area: 2.6,
    growthStage: "果实膨大期",
    phenologyProgress: 70,
    health: 98,
    ndvi: 0.86,
    soilMoisture: 74,
    rainfall14d: 58,
    elevation: 316,
    slope: 3,
    soilType: "紫色土",
    status: "healthy",
    statusLabel: "正常",
    latitude: 30.953,
    longitude: 108.709,
  },
  {
    id: "A-01",
    name: "A-01 地块",
    crop: "柑橘",
    variety: "晚熟脐橙",
    area: 3.2,
    growthStage: "果实膨大期",
    phenologyProgress: 66,
    health: 94,
    ndvi: 0.84,
    soilMoisture: 71,
    rainfall14d: 58,
    elevation: 321,
    slope: 5,
    soilType: "紫色土",
    status: "healthy",
    statusLabel: "健康",
    latitude: 30.957,
    longitude: 108.695,
  },
  {
    id: "A-08",
    name: "A-08 地块",
    crop: "柑橘",
    variety: "晚熟脐橙",
    area: 1.8,
    growthStage: "果实膨大期",
    phenologyProgress: 64,
    health: 92,
    ndvi: 0.82,
    soilMoisture: 73,
    rainfall14d: 58,
    elevation: 319,
    slope: 4,
    soilType: "紫色土",
    status: "healthy",
    statusLabel: "生长良好",
    latitude: 30.961,
    longitude: 108.704,
  },
];

export const demoMapCrops: FarmStoreState["crops"] = demoFields.map((field, index) => ({
  id: index + 1,
  date: "2026-09-04",
  latitude: field.latitude,
  longitude: field.longitude,
  url: "",
  info: {
    diseases: field.statusLabel,
    rate: 100 - field.health,
    size: field.area,
    yield: field.area,
    phenology: field.phenologyProgress,
    growth: field.health,
    impact: 100 - field.health,
    disease: field.status === "risk" ? 3 : field.status === "attention" ? 2 : 1,
    potassium: field.status === "risk" ? 1 : 2,
    phosphorus: 2,
    nitrogen: 2,
  },
}));

export const demoFarmLocations: FarmStoreState["locations"] = [
  { id: 1, latitude: 30.949, longitude: 108.691 },
  { id: 2, latitude: 30.963, longitude: 108.691 },
  { id: 3, latitude: 30.963, longitude: 108.711 },
  { id: 4, latitude: 30.949, longitude: 108.711 },
];

export const demoPrimaryField = demoFields[0];
